[build]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

[[redirects]]
  from = "/api/*"
  to = "https://cipherschools-8yuu.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
